eng_rus_dict/dictionary/urls.py
from django.urls import path

from . import views

app_name = "dictionary"

urlpatterns = [
    path('', views.home, name="home"),
    path('home/', views.home),
    path('words_list/', views.words_list, name="list"),
    path('add_word/', views.AddWordView.as_view(), name="add_word")
]

eng_rus_dict/eng_rus_dict/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("dictionary.urls", namespace="dictionary")),
    path('admin/', admin.site.urls),
]

eng_rus_dict/dictionary/models.py
from django.db import models


class EngRusWord(models.Model):
    eng = models.CharField(max_length=1000)
    rus = models.CharField(max_length=1000)
    description = models.TextField(blank=True)

eng_rus_dict/dictionary/forms.py
from django import forms
from .models import EngRusWord


class AddWord(forms.ModelForm):

    class Meta:
        model = EngRusWord
        fields = ("eng", "rus", "description")

eng_rus_dict/dictionary/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View

from .models import EngRusWord
from .forms import AddWord


def home(request):
    tittle = "My dictionary"
    context = {
        "title": tittle
    }
    return render(request=request,
                  template_name="dictionary/home.html",
                  context=context)


def words_list(request):
    words = EngRusWord.objects.all()
    context = {
        "words": words
    }
    return render(request=request,
                  template_name="dictionary/words_list.html",
                  context=context)


class AddWordView(View):
    def get(self, request):
        form = AddWord()
        context = {
            "form": form
        }
        return render(request=request,
                      template_name="dictionary/add_word.html",
                      context=context)

    def post(self, request):
        form = AddWord(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('dictionary:home'))
        else:
            print(form.errors)

eng_rus_dict/dictionary/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}{% endblock title %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {% block css %}
    {% endblock css %}

</head>

<body>
<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-black">
    <div class="container-fluid">
        <ul class="navbar-nav me-auto mb-2">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'dictionary:home' %}">HOME</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'dictionary:list' %}">List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'dictionary:add_word' %}">Add word</a>
            </li>
        </ul>
    </div>
</nav>

<main>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</main>

<script src=""></script>

</body>

eng_rus_dict/dictionary/templates/dictionary/add_word.html
{% extends "base.html" %}
{% load static %}

{% block title %} <title>{{title}}</title> {% endblock%}

{% block content %}
    <h1> Введите английское слово и перевод к нему </h1>

<form action="{% url 'dictionary:add_word' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="col-12">
        <button class="btn btn-success" type="submit">Submit</button>
    </div>
</form>
{% endblock content %}

eng_rus_dict/dictionary/templates/dictionary/home.html
{% extends "base.html" %}
{% load static %}

{% block title %} <title>{{title}}</title> {% endblock%}

{% block content %}
<h1>Home page</h1>
<img src="" alt="">
{% endblock content %}

eng_rus_dict/dictionary/templates/dictionary/words_list.html
{% extends "base.html" %}

{% load static %}

{% block title %} <title>{{title}}</title> {% endblock%}

{% block content %}

<h1>words_list</h1>

<p></p>

<table class="words_list" style="border: #515558 solid 2px">
    <th>English word</th>
    <th>Русское слово</th>
    <th>Описание</th>

    {% for word in words %}
    <tr>
        <td>{{ word.eng }}</td>
        <td>{{ word.rus }}</td>
        <td>{{ word.description }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}